### ISSUE TITLE
IndexController - gefilterte Suchanfragen einbauen

### ISSUE THREAD

**Issue by Martin-Bauer** [hu-semesterprojekt-genombrowser/Alazen-Middleware#11]
Es fehlt: 
* ~~Quelle~~
* ~~Chromosom~~
* ~~Geschlecht~~
* ~~Herkunft~~
* Relative Häufigkeit

**Comment by tobiasloeffler** [comment]
Ich habe Filter für Quelle, Chromosom, Geschlecht und Herkunft im Index hinzugefügt. Nur der Filter für die relative Häufigkeit fehlt noch. Ich werde das später alles pushen.

**Comment by BenSchumacher-HU** [comment]
Ist das fertig?

**Comment by tobiasloeffler** [comment]
Den Filter für die relative Häufigkeit bau ich morgen noch ein. Allerdings macht der Filter auf den aktuellen Daten keinen Sinn. Alle anderen Filter sind drin und funktionieren.

**Comment by tobiasloeffler** [comment]
Ich hab dazu noch eine Frage: Wenn ich jetzt z.B. einen Wert von 5 erhalte, soll ich dann alle Mutationen mit einer relativen Häufigkeit von mehr, weniger oder gleich 5% ausgeben? In der Spec habe ich dazu nichts gefunden.

**Comment by Martin-Bauer** [comment]
Gute Frage. Ich frag mal das frontend

**Comment by tobiasloeffler** [comment]
So, hab den Filter jetzt mit eingebaut und zwar so, dass Mutationen mit einer gleich hohen oder höheren relativen Häufigkeit ausgegeben werden. Bei den Tests, die ich bisher durchgeführt habe, kamen allerdings keine Mutationen doppelt vor. D.h. alle Mutationen haben die gleiche relative Häufigkeit (nämlich 1/2504).

**Comment by Martin-Bauer** [comment]
Hi, so wurde das auch vom Frontend gerade an mich zurückgegeben

Grüße,
Martin
