### ISSUE TITLE
Unit-Tests der Komponenten implementieren

### ISSUE THREAD

**Issue by Martin-Bauer** [hu-semesterprojekt-genombrowser/Alazen-Middleware#13]
am besten per junit damit alles am ende zu einer testsuite zusammengefügt werden kann
Fehlt noch bei:
* QueryReceiver (Martin)
* ~~IndexController~~
* ~~GeneTranslator~~

**Comment by BenSchumacher-HU** [comment]
Willst du das nicht in mehrere Issues aufteilen?
Nur als Hinweis: Man kann zu Issues Labels angeben. z.b. `Testing`, `Doc` oder `Feature`

**Comment by Martin-Bauer** [comment]
Für GeneTranslator erledigt

**Comment by BenSchumacher-HU** [comment]
Welche fehlen noch?

**Comment by BenSchumacher-HU** [comment]
Mit e22794a habe ich die Teste in GeneTranslatorTest.java ausgelagert. Kannst du die Tests bitte noch mit JUnit realisieren?

**Comment by Martin-Bauer** [comment]
Lieb gemeint, aber an und für sich nichtmehr nötig - Testfile für GeneTranslator ist unter testcases schon vorhanden. das unten war nur n überbleibsel der erstn hand-tests, der beim pushen von irgendwem wohl wieder aufgetaucht ist

**Comment by BenSchumacher-HU** [comment]
Ah, okay. Ich habe alle Testklassen mal in den testcases reingeschoben. Sind die alle aktuell?

**Comment by Martin-Bauer** [comment]
Ich überprüf das mal und mach sie aktuell falls nicht

**Comment by BenSchumacher-HU** [comment]
Um die Testfälle für den GeneTranslator kümmert sich @BNaber ?

**Comment by Martin-Bauer** [comment]
nope die hab ich gemacht.

**Comment by BenSchumacher-HU** [comment]
Noch Unvollständig, aber aus Zeitgründen geschlossen
