### ISSUE TITLE
Documentation in Code zufügen

### ISSUE THREAD

**Issue by Martin-Bauer** [hu-semesterprojekt-genombrowser/Alazen-Middleware#14]

**Comment by Martin-Bauer** [comment]
in Code hinzufügen

**Comment by Martin-Bauer** [comment]
Done for GeneTranslator and Index class

**Comment by BenSchumacher-HU** [comment]
Kannst du bitte auflisten, wo die Dokumentation doch fehlt. Dann ist das mit der Übersichtlichkeit einfacher. Danke dir

**Comment by Martin-Bauer** [comment]
Dokumentation fehlt in: 
QueryReceiver
IntervalST (da nur so halb, da ja vieles schon vordokumentiert war)

**Comment by tobiasloeffler** [comment]
Wieso fehlt die Dokumentation in IntervalST? Die habe ich doch gemacht. Ist die nicht ausführlich genug?

**Comment by BenSchumacher-HU** [comment]
Fehlt noch in:
* QueryReceiver.java
* Chromosome_reader.java
* Gene.java

Kurze Texte fehlen noch für:
* IndexTest.java
* PerformanceTest.java
* Query.java
* QueryAnswer.java
* createTestfile.java

@Martin-Bauer: Kannst du bitte dahinter schreiben, wer sich darum kümmer?

**Comment by BenSchumacher-HU** [comment]
Mit ffe8ecc beendet
