### ISSUE TITLE
Code an Styleguide anpassen

### ISSUE THREAD

**Issue by Martin-Bauer** [hu-semesterprojekt-genombrowser/Alazen-Middleware#15]
Fehlt noch in:
* QueryReceiver.java (Bastian)
* GeneTranslator.java (Martin)
* ~~QueryAnswer.java~~
* ~~Chromosome_reader.java~~

**Comment by BenSchumacher-HU** [comment]
Wo steht das noch aus?

**Comment by Martin-Bauer** [comment]
im IndexController und im Index wird er eingehalten. Im Rest noch nicht

**Comment by BenSchumacher-HU** [comment]
@Martin-Bauer: Kannst du bitte hinter die Datein die jeweiligen Personen schreiben? Danke dir!

**Comment by Martin-Bauer** [comment]
QueryReceiver - Bastian
Rest mach ich gleich

**Comment by BenSchumacher-HU** [comment]
Für QueryAnswer.java mit 73e63cf6f4e1e1f2f72c10a50e8a6f0bff1aeeeb abgeschlossen

**Comment by BenSchumacher-HU** [comment]
Für Chromosome_reader.java mit 7850b31e8133376072f9119af8ff5f401230fade abgeschlossen
