### ISSUE TITLE
integriertes System mit Testfällen aus Spezifikation testen [Fixing #13]

### ISSUE THREAD

**Issue by Martin-Bauer** [hu-semesterprojekt-genombrowser/Alazen-Middleware#17]
alle Fälle müssen durchlaufen und alle Anfragen müssen funktionieren

**Comment by tobiasloeffler** [comment]
Bei den Tests vom IndexController bzw. Index macht es keinen Sinn, die Testfälle aus der Spezifikation zu testen, da diese auf der alten Testdatenbank basieren. Ich werde mir neue Testfälle für die neue Testdatenbank überlegen.

**Comment by BenSchumacher-HU** [comment]
Warum lässt sich die Testdatenbank nicht verwenden?

**Comment by tobiasloeffler** [comment]
Weil die Datenbank jetzt verändert wurde, deshalb stimmen doch die Ergebnisse aus der Spezifikation nicht mehr. Das ist ja auch kein Problem, ich wollte es nur erwähnen, dass ich dafür nicht die gleichen Tests verwenden werde.

**Comment by BenSchumacher-HU** [comment]
Naja, wir möchten, wenn möglich, die Tests aus der Spezifikation durchführen. Warum können die Daten aus Spec nicht in eine Testdatenbak überführen? Dafür kann man ja eine eigene Tabelle anlegen

**Comment by tobiasloeffler** [comment]
Ja, ich kann natürlich den Index einfach aus ner Textdatei aufbauen, die die alte Datenbank enthält, aber ich dachte es wäre der Sinn der neuen Test-DB, dass wir jetzt damit testen. Ich soll ja schließlich auch die Zeitmessungen mit der neuen DB machen.

**Comment by BenSchumacher-HU** [comment]
Du hast Recht, dass sich mit der kleinen DB keine gute Messung vornehmen lässt. Dafür ist die Datenmenge übersichtlich und lässt dich einfach nachvollziehen. Deshalb bau bitte zwei Tests ein - einen mit der kleinen DB und einen mit der großen, um Performanz zu testen. Geht das?

**Comment by tobiasloeffler** [comment]
Ja, der Test aus der Spezifikation ist ja schon automatisiert und auch schon im Git hochgeladen. Ich werde so etwas ähnliches dann auch für den Performance-Test schreiben.

**Comment by BenSchumacher-HU** [comment]
Ich finde denn grade nicht. Wo liegt der?

**Comment by tobiasloeffler** [comment]
IndexTest.java und testQueries.txt. Sind aus irgendeinem Grund nur im WorkInProgress Branch.

Muss ich für den PerformanceTest wirklich JUnit benutzen, oder kann ich auch einfach ein Programm schreiben das die Anfragen einzeln durchgeht, die Laufzeiten misst und ausgibt?

**Comment by BenSchumacher-HU** [comment]
Gefunden, danke dir.
Für den PerformanceTest muss du kein JUnit benutzen. Bei diesem Test geht es ja darum, dass die Performance getestet wird, nicht die Korrektheit.

**Comment by tobiasloeffler** [comment]
Mir ist gerade aufgefallen, dass der Test aus der Spezifikation so nicht mehr funktioniert, da in der aktuellen Version immer nach Chromosom und Quelle gefiltert wird (so wie es sein soll). Das war vorher noch nicht so, deshalb sind die Ergebnismengen jetzt natürlich kleiner.
Ich würde die Testfälle jetzt einfach ein bisschen abwandeln, oder müssen es unbedingt die gleichen Testdaten sein (dann müsste ich nochmal was an der search-Funktion anpassen)?

**Comment by BenSchumacher-HU** [comment]
Du kannst die Testfälle abändern. Änder das dann bitte noch in der Spec

**Comment by tobiasloeffler** [comment]
Ok, hab alles abgeändert.

**Comment by BenSchumacher-HU** [comment]
Deckt sich diese Issue nicht mit #13 und ist redundant?

**Comment by Martin-Bauer** [comment]
an und für sich inzwischen schon - hiermit war eher gemeint, dass alle komponenten zusammen getestet werden

**Comment by BenSchumacher-HU** [comment]
Meinst du damit den Stresstest?

**Comment by Martin-Bauer** [comment]
Hmm stimtm, das kommt dem ja inhaltlisch gleich - Dann kann der 
geschlossen werden :)
