### ISSUE TITLE
Memory Bug auf Server fixen

### ISSUE THREAD

**Issue by Martin-Bauer** [hu-semesterprojekt-genombrowser/Alazen-Middleware#25]
Beim starten des TOmcat baut sich zwar der Index,
allerdings beendet dieser Prozess nach geraumer Zeit mit einer Fehlermeldung:

OpenJDK 64-Bit Server VM warning: INFO:
os::commit_memory(0x00000006bbe00000, 482869248, 0) failed; error='Nicht
genügend Hauptspeicher verfügbar' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 482869248 bytes for
committing reserved memory.
# An error report file with more information is saved as:
# /home/postgres_user/Query_Answer_fix/hs_err_pid18051.log

Das muss schnellstmöglich gefixed werden, da sonst die db nicht ausgelesen werden kann und das system nicht ansprechbar ist

**Comment by BenSchumacher-HU** [comment]
Naja, das Problem ist ja beschrieben: Er kann keinen RAM allocieren. 
Laut top sind auch "nur " 1.5Gb noch frei, das dürfte ein wenig knapp sein.
Man kann sich die Prozesse nach RAM verbrauch sortieren laasen  `ps aux --sort rss` für realen RAM-Verbrauch und `ps aux --sort vsz` - siehe auch [hier](http://stackoverflow.com/questions/7880784/what-is-rss-and-vsz-in-linux-memory-management) 
Dann sieht man, dass der realte RAM verbrauch nicht so groß ist. Versucht es nochmal und guckt euch nebenbei die Statistik an. Kann man an dem RAM verbrauch noch was tun? Weniger Variablen instantiieren? Habe ihr eine Idee, wobei am meisten RAM verwendet wird?

**Comment by tobiasloeffler** [comment]
Also ich habe eine Idee wie ich den Speicherplatz verringern kann. Das werde ich jetzt ausprobieren. Das große Problem ist ja, dass der Fehler schon kommt wenn man den Index nur für Chromosom 1 baut (12 Mio. Mutationen, ca. 2GB). Am Ende wollen wir ja aber die 16GB (fast) komplett nutzen. Das wird dann noch schwieriger.

**Comment by BenSchumacher-HU** [comment]
Ich stehe grade auf dem Schlauch. Haben die beiden anderen VMs nicht eigenen RAM, der dann verwendet wird?

**Comment by tobiasloeffler** [comment]
Ja, aber der Index läuft ja noch nicht verteilt. Und selbst wenn er verteilt läuft, dann darf es keine Fehler geben nur weil wir 1/8 des RAMs verwenden wollen.

**Comment by tobiasloeffler** [comment]
Update: Ich hab den Speicherverbrauch um ca. 30% reduziert, aber das verzögert den Fehler einfach nur. Jetzt bekomme ich den immer am Anfang des 2. Chromosoms. Das komische ist aber, dass der Heap noch lange nicht voll ist, deshalb verstehe ich nicht wieso er keinen Speicher mehr allocieren kann.

**Comment by tobiasloeffler** [comment]
So, ich hab meine bisherigen Änderungen mal gepusht.

**Comment by BenSchumacher-HU** [comment]
Hat sich dadurch was verbessert?

**Comment by tobiasloeffler** [comment]
Verbessert ja, aber es behebt das Problem nicht.

**Comment by BenSchumacher-HU** [comment]
Ich habe grade keine Zugriff auf die VM. Wie sieht es mit RAM aus? Wann stürzt die VM ab?

**Comment by tobiasloeffler** [comment]
Bei ca. 2,5 GB glaube ich.

**Comment by BenSchumacher-HU** [comment]
Hat sich das Problem erledigt?
