### ISSUE TITLE
subintervals in QueryAnswer

### ISSUE THREAD

**Issue by BenSchumacher-HU** [hu-semesterprojekt-genombrowser/Alazen-Middleware#26]
Ist es gewollt, dass QueryAnswer das Attribut subintervals besitzt, es aber im Konstruktor nicht vorkommt?

**Comment by tobiasloeffler** [comment]
Ich glaube nicht. Wir haben nur vergessen das zu löschen.

**Comment by BenSchumacher-HU** [comment]
Mit 9f62ad68f52bef6ec97cf22bb47c04329723b22f entfernt

**Comment by BenSchumacher-HU** [comment]
Mit 9f62ad68f52bef6ec97cf22bb47c04329723b22f entfernt
