### ISSUE TITLE
Ant File anpassen

### ISSUE THREAD

**Issue by BenSchumacher-HU** [hu-semesterprojekt-genombrowser/Alazen-Middleware#4]
Die Datei build.xml muss an eure Struktur angepasst werden.
Einer Erklärung, wie Ant funktioniert, ist unter [https://ant.apache.org/manual/tutorial-HelloWorldWithAnt.html] zu finden. 

Es fehlt doch:
* Tests bauen und ausführen
* ~~Dokumentation bauen~~

**Comment by Martin-Bauer** [comment]
Das sollte jetzt so stimmen für unser Projekt denk ich. Schau mal drüber und sag, ob noch was rein soll, bzw was noch fehlt

**Comment by BenSchumacher-HU** [comment]
Zunächst bekomme ich, wenn ich bauen will einen:
` [java] Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException:`
`     [java] 	at Genomindex.main(Unknown Source) `
`     [java] Java Result: 1`.
Dann solltet ihr noch ein Target bauen, dass alle Tests aufführt. Wenn du willst, auch für jeden Test ein Target.

**Comment by Martin-Bauer** [comment]
Ja das Ziel run könnte eh etwas schwierig werden letztendlich, da wir ja nur bedingt ne Main-Klasse haben. Der Plan ist ja servlets zu nutzen, die werden aber über ne init() & ne service()-funktion aufgerufen und nicht über ne main-methode. Und die aufrufe machen ja auch nur sinn, wenn ne anfrage mitgeschickt wird. 
Ich bin mir deshalb grad unsicher, was das run-ziel denn dann machen sollte. Tests ausführen ist ja eher unwahrscheinlich, weil es dafür targets geben soll. Das Programm einmal ohne aufruf starten ist Auch suboptimal, weil ja im Endeffekt nix passieren wird. 
Und ne version die anfragen annimt haben wir ja durch dne Stresstest irgendwie schon.

**Comment by BenSchumacher-HU** [comment]
Wenn du den sportlichen Weg nehmen willst, versuchst du das Servlet in das Ant mit einbauen, siehe [hier](https://ant.apache.org/manual/Tasks/war.htmla) und [hier](http://www.avajava.com/tutorials/lessons/how-do-i-compile-my-project-using-ant.html). Ansonsten erstellst du nur Targets für die Tests und es gibt kein großes Run Target. Das bauen des Servlets mit Ant lege ich dir trotzdem ans Herzen, da es das Depolyment auf die VMs einfacher macht

**Comment by BenSchumacher-HU** [comment]
Im Moment bekomme ich diese : 
```
    [javac] /home/bschumacher/Documents/uni/5.Semester/VGB/alazenMiddleware/src/IndexController.java:19: error: cannot find symbol
    [javac]     x_CountryMap = new TObjectShortHashMap<String>();
    [javac]                        ^
    [javac]   symbol:   class TObjectShortHashMap
    [javac]   location: class IndexController
    [javac] /home/bschumacher/Documents/uni/5.Semester/VGB/alazenMiddleware/src/IndexControllerTest.java:13: error: cannot find symbol
    [javac]     IntervalST.Query x_Query[] = new IntervalST.Query[1];
    [javac]               ^
    [javac]   symbol:   class Query
    [javac]   location: class IntervalST
    [javac] /home/bschumacher/Documents/uni/5.Semester/VGB/alazenMiddleware/src/IndexControllerTest.java:13: error: cannot find symbol
    [javac]     IntervalST.Query x_Query[] = new IntervalST.Query[1];
    [javac]                                                ^
    [javac]   symbol:   class Query
    [javac]   location: class IntervalST
    [javac] /home/bschumacher/Documents/uni/5.Semester/VGB/alazenMiddleware/src/IndexControllerTest.java:18: error: cannot find symbol
    [javac]         x_Query[0] = new IntervalST.Query(1, Integer.parseInt(x_Parts[0]), Integer.parseInt(x_Parts[1]), Short.parseShort(x_Parts[2]), x_Parts[3].getBytes(), null, null, true, false, 1);
    [javac]                                    ^
    [javac]   symbol:   class Query
    [javac]   location: class IntervalST
    [javac] /home/bschumacher/Documents/uni/5.Semester/VGB/alazenMiddleware/src/IndexControllerTest.java:20: error: cannot find symbol
    [javac]         x_Query[0] = new IntervalST.Query(1, Integer.parseInt(x_Parts[0]), Integer.parseInt(x_Parts[1]), Short.parseShort(x_Parts[2]), x_Parts[3].getBytes(), x_Parts[4].getBytes(), null, true, false, 1);
    [javac]                                    ^
    [javac]   symbol:   class Query
    [javac]   location: class IntervalST
    [javac] /home/bschumacher/Documents/uni/5.Semester/VGB/alazenMiddleware/src/IndexControllerTest.java:22: error: cannot find symbol
    [javac]         x_Query[0] = new IntervalST.Query(1, Integer.parseInt(x_Parts[0]), Integer.parseInt(x_Parts[1]), Short.parseShort(x_Parts[2]), x_Parts[3].getBytes(), x_Parts[4].getBytes(), x_Parts[5].getBytes(), true, false, 1);
    [javac]                                    ^
    [javac]   symbol:   class Query
    [javac]   location: class IntervalST
```
Fehlermeldung. Hast du eine Idee, woran das liegt? Schreibst du dann ein Issue an die entsprechende Person?

**Comment by BenSchumacher-HU** [comment]
Mit  5320670  wird die Dokumentation gebaut

**Comment by BenSchumacher-HU** [comment]
Bezüglich der Tests kann man sich auch die Datei der Integration angucken
[https://github.com/hu-semesterprojekt-genombrowser/Alazen-Integration/blob/master/build.xml]

**Comment by Martin-Bauer** [comment]
Ja, da fehlt eine Library im classpath, die neu reinkam. ich änder das gleich ab

**Comment by Martin-Bauer** [comment]
Bauen des servlets ist fertig.
Bauen und ausfüren der testfälle fehlt noch

**Comment by BenSchumacher-HU** [comment]
Abgeschlossen
