### ISSUE TITLE
Continuous Integration einbauen

### ISSUE THREAD

**Issue by BenSchumacher-HU** [hu-semesterprojekt-genombrowser/Alazen-Middleware#6]
Nachdem #4 beendet wurde, soll der Buildprozess und das Laufen der Testprogramme in Travis eingebaut werden.
Bei Fragen an [Ben](@BenSchumacher-HU) wenden

**Comment by Martin-Bauer** [comment]
Hier Frage:
Was genau soll in travis eingebaut werden. Sollen die Testfiles alle durchlaufen, so dass nach nem commit geschaut werden kann ob die laufen oder wie? Wenn ja bräucht ich eine kurze Einführung, wie ich das in Travis reinpacke

**Comment by BenSchumacher-HU** [comment]
Ja, genau das soll ein Travis rein. Dafür muss du das Antfile anpassen, wie auch im Kommentar geschrieben. Den Einbau in Travis mach ich dann. Alles klar?

**Comment by Martin-Bauer** [comment]
Alles klar

**Comment by BenSchumacher-HU** [comment]
:+1:  :smile:

**Comment by BenSchumacher-HU** [comment]
Abgeschlossen
